# config/settings.yaml
zonas:
  sala:
    nombre: "Sala de Estar"
    icono: "sofa"
    dispositivos:
      ventilador_sala:
        nombre: "Ventilador DREO"
        tipo: "ventilador"
        estado: false
        velocidad: 1
        modo: "normal"
        oscilacion: false
        mqtt:
          sub_topic: "casa/sala/ventilador/estado"
          pub_topic: "casa/sala/ventilador/comando"